import React,{useEffect,useState}from'react';import*as XLSX from 'xlsx';
const API=import.meta.env.VITE_API_URL||'';
const blank=()=>({area:'',beforeFile:null,beforeUrl:'',issue:'',description:'',action:'',person:'',date:'',afterFile:null,afterUrl:'',status:'Open',signature:''});
const areas=['Cutting','Sewing','Ironing','Packing','Embroidery','CAD','Office','Canteen','Chemical Storage','Boiler','ETP','Yarn Dyeing','Fabric Washing','Garment Washing','Other'];
async function call(action,payload={}){if(!API)throw Error('Set VITE_API_URL in .env first');const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})});const j=await r.json();if(!j.ok)throw Error(j.error||'Request failed');return j.data;}
function App(){const [form,S]=useState(blank()),[rows,R]=useState([]),[busy,B]=useState(false),[msg,M]=useState(''),[filter,F]=useState(new Date().toISOString().slice(0,10));const set=(k,v)=>S(p=>({...p,[k]:v}));
async function imageData(file){if(!file)return null;return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res({name:file.name,mimeType:file.type,data:String(fr.result).split(',')[1]});fr.onerror=rej;fr.readAsDataURL(file);});}
async function analyze(){if(!form.beforeFile){M('Upload a before image first.');return;}B(true);M('Analysing image…');try{const im=await imageData(form.beforeFile);const d=await call('analyze',{image:im,area:form.area});S(p=>({...p,issue:d.issue||p.issue,description:d.description||p.description,action:d.action||p.action}));M('AI draft created. Review and edit before saving.');}catch(e){M(e.message)}finally{B(false)}}
async function save(e){e.preventDefault();if(!form.area||!form.beforeFile||!form.issue||!form.person||!form.date){M('Complete area, before image, issue, responsible person and completion date.');return;}B(true);M('Saving observation…');try{const before=await imageData(form.beforeFile),after=await imageData(form.afterFile);await call('save',{record:{...form,beforeFile:undefined,afterFile:undefined},before,after});M('Observation saved to Google Sheets and Drive.');S(blank());await load();}catch(e){M(e.message)}finally{B(false)}}
async function load(){try{const d=await call('list');R(d||[])}catch(e){M(e.message)}}useEffect(()=>{if(API)load()},[]);
function exportXlsx(){const headings=['S. No','Area of Inspection','Before image','Issue','Description','Action to be taken','Responsible person','Signature','After Image','Complete date','Status'];const data=[headings,...rows.map((r,i)=>[i+1,r.area,r.beforeUrl||'',r.issue,r.description,r.action,r.person,r.signature||'',r.afterUrl||'',r.date,r.status])];const ws=XLSX.utils.aoa_to_sheet(data);ws['!cols']=[{wch:7},{wch:22},{wch:28},{wch:30},{wch:48},{wch:48},{wch:24},{wch:20},{wch:28},{wch:16},{wch:16}];ws['!rows']=[{hpt:30},...rows.map(()=>({hpt:70}))];ws['!autofilter']={ref:`A1:K${data.length}`};const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Daily EHS Report');XLSX.writeFile(wb,`EHS_Daily_Report_${filter||'All'}.xlsx`);}
return <main><header><div><small>ENVIRONMENT • HEALTH • SAFETY</small><h1>EHS Daily Observation Report</h1><p>Record observations, assign actions and track closure.</p></div><button className="secondary" onClick={exportXlsx}>Export Excel</button></header><section className="panel"><h2>New observation</h2><form onSubmit={save}><div className="grid"><label>Area of Inspection *<select value={form.area} onChange={e=>set('area',e.target.value)} required><option value="">Choose area</option>{areas.map(a=><option key={a}>{a}</option>)}</select></label><label>Before Image *<input type="file" accept="image/*" capture="environment" onChange={e=>set('beforeFile',e.target.files[0])} required/></label></div><button type="button" disabled={busy} onClick={analyze}>✨ Analyse image with AI</button><div className="grid"><label>Issue *<input value={form.issue} onChange={e=>set('issue',e.target.value)} required/></label><label>Responsible person *<input value={form.person} onChange={e=>set('person',e.target.value)} required/></label></div><label>Description<textarea rows="3" value={form.description} onChange={e=>set('description',e.target.value)}/></label><label>Action to be taken<textarea rows="3" value={form.action} onChange={e=>set('action',e.target.value)}/></label><div className="grid"><label>Completion date *<input type="date" value={form.date} onChange={e=>set('date',e.target.value)} required/></label><label>Status<select value={form.status} onChange={e=>set('status',e.target.value)}>{['Open','In Progress','Completed','Overdue'].map(x=><option>{x}</option>)}</select></label></div><div className="grid"><label>After Image<input type="file" accept="image/*" capture="environment" onChange={e=>set('afterFile',e.target.files[0])}/></label><label>Signature / acknowledgement<input value={form.signature} onChange={e=>set('signature',e.target.value)} placeholder="Type name or acknowledgement"/></label></div><button disabled={busy}>{busy?'Please wait…':'Save observation'}</button></form>{msg&&<p className="message">{msg}</p>}</section><section className="panel"><div className="listhead"><h2>Observation register</h2><button className="secondary" onClick={load}>Refresh</button></div><p className="muted">Records retrieved from the connected Google Sheet.</p><div className="tablewrap"><table><thead><tr>{['Area','Issue','Responsible person','Complete date','Status'].map(x=><th>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}><td>{r.area}</td><td>{r.issue}</td><td>{r.person}</td><td>{r.date}</td><td><span className="pill">{r.status}</span></td></tr>)}</tbody></table></div></section><footer>AI-generated content is a draft. Verify hazards and corrective actions before issuing.</footer></main>}
export default App;
